name: CI Pipeline

on:
  push:
    branches: [ master, new-feature ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Success message
        run: |
          echo "GitHub Actions работает!"
          echo "Ветка: ${{ github.ref }}"
          ls -la
